name: over_react
version: 4.1.0
description: A library for building statically-typed React UI components using Dart.
homepage: https://github.com/Workiva/over_react/
environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  collection: ^1.15.0
  analyzer: ^1.7.2
  build: ^2.0.3
  dart_style: ^2.0.3
  js: ^0.6.3
  logging: ^1.0.1
  memoize: ^3.0.0
  meta: ^1.7.0
  path: ^1.8.0
  react: ^6.0.0
  redux: ^5.0.0
  source_span: ^1.8.1
  transformer_utils: ^0.2.6
  w_common: ^1.13.0
  w_flux: ^2.10.4
  platform_detect: ^2.0.0
  quiver: ^3.0.1
  redux_dev_tools: ^0.7.0

dev_dependencies:
  build_resolvers: ^2.0.4
  build_runner: ^2.0.6
  build_test: ^2.1.2
  build_web_compilers: ^3.0.0
#  dart_dev: ^3.6.4
  glob: ^2.0.1
  io: ^1.0.3
  mockito: ^5.0.12
  over_react_test: ^2.10.2
  pedantic: ^1.11.1
  test: ^1.17.10
  yaml: ^3.1.0

dependency_overrides:
  react:
    git:
      url: https://github.com/Workiva/react-dart.git
      ref: null-safety-manual
  transformer_utils:
    git:
      url: git@github.com:Workiva/dart_transformer_utils.git
      ref: null-safety


workiva:
  core_checks:
    version: 1
    react_boilerplate: disabled
