name: over_react
version: 1.29.0
description: A library for building statically-typed React UI components using Dart.
homepage: https://github.com/Workiva/over_react/
authors:
  - Workiva UI Platform Chapter <uip@workiva.com>
  - Workiva App Frameworks Team <appframeworks@workiva.com>
environment:
  sdk: '>=1.24.2 <=3.0.0'
dependencies:
  analyzer: ">=0.30.0 <=0.33.3"
  built_redux: ^7.4.2
  built_value: ^5.4.4
  js: ^0.6.1+1
  logging: ">=0.11.3+2 <1.0.0"
  meta: ^1.1.6
  path: ^1.5.1
  react: ^4.4.2
  source_span: ^1.4.1
  w_common: ^1.13.0
  w_flux: ^2.9.5
  platform_detect: ^1.3.4
  quiver: ">=0.25.0 <1.0.0"
dev_dependencies:
  build: ^1.0.0
  build_runner_core: any
  build_runner: any #^0.9.0
  build_test: any #^0.10.3
  build_web_compilers: any
  built_value_generator: any #^5.3.0
  coverage: ">=0.10.0 <0.12.4"
  dart2_constant: ^1.0.0
  dart_dev: ">=1.9.6 <3.0.0"
  dependency_validator: ^1.2.2
  mockito: any #^2.2.3
  #over_react_test: any #^1.5.0
  source_gen: any #^0.7.4+3
  test: '>=0.12.30 <2.0.0'
  transformer_utils: ^0.1.5

dependency_overrides:
  built_redux:
    git:
      url: git@github.com:corwinsheahan-wf/built_redux.git
      ref: 9c9580242e8af6b905ef26c452600dca2195a98b # from bump_build_runner
  transformer_utils:
    git:
      url: git@github.com:workiva/dart_transformer_utils.git
      ref: cc2200ab8e6fb408899b64e53b4aedb0ac69ca5f # from dart2_compat
