name: over_react
publish_to: https://pub.workiva.org
version: 1.0.0
description:
homepage: https://github.com/Workiva/over_react/
authors:
  - Workiva UI Platform Team <uip@workiva.com>
environment:
  sdk: ">=1.17.1"
dependencies:
  analyzer: ">=0.26.1+3 <0.28.0"
  barback: "^0.15.0"
  react: "^3.0.0"
  source_span: "^1.2.0"
  transformer_utils: "^0.1.1"
dev_dependencies:
  matcher: ">=0.11.0 <0.13.0"
  coverage: "^0.7.2"
  dart_dev: "^1.0.5"
  markdown: "^0.8.0"
  mockito: "^0.11.0"
  test: "^0.12.6+2"

transformers:
  - over_react:
      $exclude: [
        "test/ui_core/component_declaration/transformer_helpers_test.dart"
      ]
  - test/pub_serve:
      $include: test/**_test{.*,}.dart
  # Reminder: dart2js should come after any other transformers that touch Dart code
  - $dart2js
