name: over_react
version: 1.22.0
description: A library for building statically-typed React UI components using Dart.
homepage: https://github.com/Workiva/over_react/
authors:
  - Workiva UI Platform Chapter <uip@workiva.com>
  - Workiva App Frameworks Team <appframeworks@workiva.com>
environment:
  sdk: ">=1.24.2"
dependencies:
  analyzer: ">=0.30.0 <0.31.0"
  barback: ^0.15.0
  built_redux: ">=6.1.0 < 8.0.0"
  built_value: ">=4.2.0 <6.0.0"
  js: ^0.6.0
  logging: ">=0.11.3+1 <1.0.0"
  meta: ^1.0.4
  path: ^1.4.1
  react: ^3.7.0
  source_span: ^1.4.0
  transformer_utils: ^0.1.1
  w_common: ^1.8.0
  w_flux: ^2.7.1
  platform_detect: ^1.3.2
  quiver: ">=0.21.4 <0.26.0"
dev_dependencies:
  build_runner: ^0.6.0
  built_value_generator: ^5.1.3
  coverage: ^0.7.2
  dart_dev: ^1.7.6
  dependency_validator: ^1.0.0
  mockito: ^0.11.0
  over_react_test: ^1.2.0
  source_gen: ^0.7.2+1
  test: ^0.12.24

transformers:
  - over_react:
      $exclude: [
        "test/over_react/component_declaration/transformer_helpers_test.dart"
      ]
  - test/pub_serve:
      $include: test/**_test{.*,}.dart
  # Reminder: dart2js should come after any other transformers that touch Dart code
  - $dart2js:
      csp: true
      sourceMaps: true
      minify: true
      suppressHints: false
      commandLineOptions:
        - --verbose
        - --dump-info
        - --use-new-source-info
        - --show-package-warnings
        - --enable-experimental-mirrors
