name: over_react
version: 1.24.1
description: A library for building statically-typed React UI components using Dart.
homepage: https://github.com/Workiva/over_react/
authors:
  - Workiva UI Platform Chapter <uip@workiva.com>
  - Workiva App Frameworks Team <appframeworks@workiva.com>
environment:
  sdk: '>=2.0.0-dev.0 <=2.0.0-dev.49.0'
dependencies:
  analyzer: ">=0.30.0 <0.32.0"
  barback: ">=0.15.2 <=0.15.2+14"
  built_redux: ^7.4.1
  built_value: ">=4.2.0 <5.2.0" # >=5.2.0 is Dart 2 SDK only
  js: ^0.6.0
  logging: ">=0.11.3+1 <1.0.0"
  meta: ^1.0.4
  path: ^1.4.1
  react: ^4.4.1
  source_span: ^1.4.0
  transformer_utils: ^0.1.1
  w_common: ^1.10.0
  w_flux: ^2.7.1
  platform_detect: ^1.3.2
  quiver: ">=0.21.4 <0.29.0"
dev_dependencies:
  build_runner: ^0.6.0
  built_value_generator: ^5.1.3
  coverage: ">=0.7.2 <0.12.0"
  dart2_constant: ^1.0.0
  dart_dev: ^1.7.6
  dependency_validator: ^1.1.0
  mockito: ^2.0.0
  over_react_test: ^1.2.0
  source_gen: ^0.7.2+1
  test: ^0.12.32+1

transformers:
  - over_react:
      $exclude: [
        "test/over_react/component_declaration/transformer_helpers_test.dart"
      ]
  - test/pub_serve:
      $include: test/**_test{.*,}.dart
  # Reminder: dart2js should come after any other transformers that touch Dart code
  - $dart2js:
      csp: true
      sourceMaps: true
      minify: true
      suppressHints: false
      commandLineOptions:
        - --verbose
        - --dump-info
        - --use-new-source-info
        - --show-package-warnings
        - --enable-experimental-mirrors


dependency_overrides:
  react:
    git:
      url: git@github.com:aaronlademann-wf/react-dart.git
      ref: 71aa22ee67e68526f619a1b120d55a6b001721fc # from 5.0.0/AF-222
  over_react_test:
    git:
      url: git@github.com:Workiva/over_react_test.git
      ref: 4d23297dcd7dc482368fb5aac65b9c0560719350 # from dart2_prep

