name: over_react
version: 1.10.0
description: A library for building statically-typed React UI components using Dart.
homepage: https://github.com/Workiva/over_react/
authors:
  - Workiva UI Platform Team <uip@workiva.com>
environment:
  sdk: ">=1.21.1"
dependencies:
  analyzer: ">=0.26.1+3 <0.31.0"
  barback: "^0.15.0"
  js: "^0.6.0"
  meta: "^1.0.4"
  path: "^1.4.1"
  react: "^3.1.0"
  source_span: "^1.2.0"
  transformer_utils: "^0.1.1"
  w_flux: "^2.5.0"
  platform_detect: "^1.3.2"
  quiver: ">=0.21.4 <0.25.0"
dev_dependencies:
  matcher: ">=0.11.0 <0.13.0"
  coverage: "^0.7.2"
  dart_dev: "^1.0.5"
  mockito: "^0.11.0"
  test: "^0.12.6+2"

transformers:
  - over_react:
      $exclude: [
        "test/over_react/component_declaration/transformer_helpers_test.dart"
      ]
  - test/pub_serve:
      $include: test/**_test{.*,}.dart
  # Reminder: dart2js should come after any other transformers that touch Dart code
  - $dart2js
