name: over_react
version: 2.4.4+dart2
description: A library for building statically-typed React UI components using Dart.
homepage: https://github.com/Workiva/over_react/
authors:
  - Workiva UI Platform Chapter <uip@workiva.com>
  - Workiva App Frameworks Team <appframeworks@workiva.com>
environment:
  sdk: '>=2.2.2 <3.0.0'

dependencies:
  analyzer: '>=0.35.0 <0.37.0'
  build: ^1.0.0
  built_redux: ^7.4.2
  built_value: '>=5.4.4 <7.0.0'
  dart_style: '>=0.1.7 <2.0.0'
  js: ^0.6.1+1
  logging: ">=0.11.3+2 <1.0.0"
  meta: ^1.1.6
  path: ^1.5.1
  react: ^4.9.0
  source_span: ^1.4.1
  transformer_utils: ^0.2.0
  w_common: ^1.13.0
  w_flux: ^2.9.5
  platform_detect: ^1.3.4
  quiver: ">=0.25.0 <1.0.0"
dev_dependencies:
  build_resolvers: ^1.0.5
  build_runner: ^1.5.2
  build_test: ^0.10.8
  build_web_compilers: ^2.1.1
  built_value_generator: ^6.0.0
  dart2_constant: ^1.0.0
  dart_dev: ^2.0.0
  dependency_validator: ^1.2.2
  mockito: ^4.0.0
  over_react_test: ^2.5.0
  test: ^1.0.0

dependency_overrides:
  react:
    git:
      url: https://github.com/cleandart/react-dart.git
      ref: 5.1.0-wip
