name: over_react
version: 4.1.0
description: A library for building statically-typed React UI components using Dart.
homepage: https://github.com/Workiva/over_react/
authors:
  - Workiva UI Platform Chapter <uip@workiva.com>
  - Workiva App Frameworks Team <appframeworks@workiva.com>
environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  collection: ^1.14.11
  analyzer: '>=0.42.0'
  build: '<3.0.0'
  built_redux:
    git:
      url: git@github.com:hunterbreathat-wk/built_redux.git
      ref: flutter-fix
  built_value: ^8.0.0-nullsafety.0
  dart_style: ^1.2.5
  js: ^0.6.1+1
  logging: ^1.0.0
  memoize: ^2.0.0
  meta: ^1.1.6
  path: ^1.5.1
  react: ^6.0.0
  redux: ">=3.0.0 <5.0.0"
  source_span: ^1.4.1
  transformer_utils:
    git:
      url: git@github.com:hunterbreathat-wk/dart_transformer_utils.git
      ref: flutter-fix
  w_common:
    git:
      url: git@github.com:Workiva/w_common.git
      ref: w-common-flutter-fix-new
  w_flux:
    git:
      url: git@github.com:kyleferguson-wk/w_flux.git
      ref: flutter-fix
  platform_detect:
    git:
      url: git@github.com:kyleferguson-wk/platform_detect.git
      ref: flutter-fix
  quiver: ">=0.25.0 <3.0.0"
  redux_dev_tools: ">=0.4.0 <0.6.0"

dev_dependencies:
  build_resolvers: ^2.0.0
  build_runner: ^1.7.1
  build_test: ^2.0.0
  build_web_compilers: ^2.5.1
  built_value_generator: ^8.0.0-nullsafety.0
  dart2_constant: ^1.0.0
  dart_dev:
    git:
      url: git@github.com:kyleferguson-wk/dart_dev.git
      ref: master
  dependency_validator:
    git:
      url: git@github.com:kyleferguson-wk/dependency_validator.git
      ref: master
  glob: ^2.0.0
  io: ^0.3.2+1
  mockito: ^4.1.1
  over_react_test: ^2.10.2
  pedantic: ^1.8.0
  test: ^1.9.1
  yaml: ^3.0.0

workiva:
  core_checks:
    version: 1
    react_boilerplate: disabled