name: over_react
version: 2.5.0+dart1
description: A library for building statically-typed React UI components using Dart.
homepage: https://github.com/Workiva/over_react/
authors:
  - Workiva UI Platform Chapter <uip@workiva.com>
  - Workiva App Frameworks Team <appframeworks@workiva.com>
environment:
  sdk: ">=1.24.2 <2.0.0"
dependencies:
  analyzer: ">=0.30.0+4 <=0.31.1"
  barback: ">=0.15.2 <=0.15.2+14"
  built_redux: ^7.4.2
  built_value: ">=4.6.1 <5.2.0" # >=5.2.0 is Dart 2 SDK only
  js: ^0.6.1+1
  logging: ">=0.11.3+2 <1.0.0"
  meta: ^1.1.6
  path: ^1.5.1
  react: ^4.9.0
  source_span: ^1.4.1
  transformer_utils: ^0.1.5
  w_common: ^1.13.0
  w_flux: ^2.9.5
  platform_detect: ^1.3.4
  quiver: ">=0.25.0 <=0.28.0" # 0.28.0+ is Dart 2 only
dev_dependencies:
  build_runner: ^0.6.0+1
  built_value_generator: ^5.1.3
  coverage: ">=0.10.0 <0.11.0" # 0.11.0+ is Dart 2 only
  dart2_constant: ^1.0.0
  dart_dev: ^1.9.6
  dependency_validator: ^1.2.2
  mockito: ^2.2.2
  over_react_test: '>=1.6.0 <3.0.0'
  source_gen: ^0.7.4+3
  test: ^0.12.34

transformers:
  - over_react:
      $exclude: [
        "test/over_react/component_declaration/transformer_helpers_test.dart"
      ]
  - test/pub_serve:
      $include: test/**_test{.*,}.dart
  # Reminder: dart2js should come after any other transformers that touch Dart code
  - $dart2js:
      csp: true
      sourceMaps: true
      minify: true
      suppressHints: false
      commandLineOptions:
        - --verbose
        - --dump-info
        - --use-new-source-info
        - --show-package-warnings
        - --enable-experimental-mirrors
