name: todo_client
version: 1.0.0

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  color: any
  memoize: ^2.0.0
  meta: ">=1.2.2 <1.7.0" # Workaround to avoid https://github.com/dart-lang/sdk/issues/46142
  over_react: ">=3.1.5 <5.0.0"
  json_annotation: ^3.0.0
  redux: ">=3.0.0 <5.0.0"
  redux_dev_tools: ">=0.4.0 <0.6.0"
  uuid: ^1.0.3

dev_dependencies:
  build_runner: ^1.7.1
  build_web_compilers: ^2.12.0
  build_test: ">=0.10.9 <2.0.0"
  dart_dev: ^3.0.0
  glob: ^1.2.0
  json_serializable: ^3.2.2
  over_react_test: ^2.10.2
  pedantic: ^1.8.0
  test: ^1.15.7
  test_html_builder: ^1.0.0
  time: ^1.2.0
  w_common: ^1.20.0
  workiva_analysis_options: ^1.1.0

dependency_overrides:
  over_react:
    path: '../../../'
