name: builder_utils
version: 0.1.0
description: Utilities relating to code generation, Dart analyzer, logging, etc. for use in dart builders.
authors:
  - Workiva UI Platform Team <uip@workiva.com>
  - Workiva Client Platform Team <cp@workiva.com>
  - Greg Littlefield <greg.littlefield@workiva.com>
  - Evan Weible <evan.weible@workiva.com>
#homepage: https://github.com/Workiva/dart_transformer_utils
dependencies:
  analyzer: ">=0.27.0 <0.33.0"
  path: "^1.3.0"
  source_span: "^1.2.0"
  dart2_constant: ^1.0.1

dev_dependencies:
  build_runner: ^1.0.0
  coverage: ">=0.10.0 <0.13.0"
  dart_dev: ">=1.9.2 <3.0.0"
  dart_style: ^1.0.9
  dependency_validator: ^1.1.0
  mockito: ">=2.0.0 <4.0.0"
  test: ">=0.12.32+1 <2.0.0"

environment:
    sdk: ">=1.24.2 <3.0.0"
