name: plugin_playground
version: 0.0.0
environment:
  sdk: '>=2.7.0 <3.0.0'
dependencies:
  over_react: ^4.1.0
dev_dependencies:
  build_runner: ^1.0.0
  build_web_compilers: ^2.0.0
  workiva_analysis_options: ^1.1.0

dependency_overrides:
  # Pull in the local copy of over_react so it pulls in the local copy of the plugin
  over_react:
      path: ../../..
