name: import_over_react_test
version: 0.0.1
description: Test importing over_react
environment:
  sdk: ">=1.19.1 <2.0.0"
dependency_overrides:
  react:
    git:
      url: git://github.com/evanweible-wf/react-dart.git
      ref: unconvertJsProps
dependencies:
  browser: ">=0.10.0 <0.11.0"
  over_react:
    git:
      url: git://127.0.0.1:9000/
      ref: HEAD
dev_dependencies:
  dart_dev: ^1.9.2
  test: ^0.12.32+1
transformers:
  - test/pub_serve:
      $include: test/test_runtime_import.dart
